// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Azure Logic App Monitoring")]
[assembly: AssemblyProductAttribute("Azure Logic App Monitoring")]
[assembly: AssemblyDescriptionAttribute("Azure Logic App Monitoring")]
[assembly: AssemblyVersionAttribute("1.0.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0.1";
        internal const string InformationalVersion = "1.0.0.1";
    }
}
